# Generated by Django 4.1.7 on 2023-02-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='key',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
