# Generated by Django 4.1.7 on 2023-02-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='key',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya existe una sala con esta key'}, max_length=6, unique=True),
        ),
    ]
