# Generated by Django 4.1.7 on 2023-02-19 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('status', models.BooleanField(default=True, help_text='Solo los usuarios activos pueden iniciar sesión', verbose_name='Estado del usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
